# Generated by Django 3.1.6 on 2021-06-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcontract_details', models.TextField(default='', max_length=20)),
                ('ktermination', models.TextField(default='', max_length=30)),
                ('kpromotions', models.TextField(default='', max_length=30)),
                ('position', models.TextField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwork_experience', models.TextField(default='', max_length=50)),
                ('gseminars_attended', models.TextField(default='', max_length=50)),
                ('gskills', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcompany_branch', models.TextField(default='', max_length=15)),
                ('bcompany_address', models.TextField(default='', max_length=20)),
                ('bcontact_number', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcompany_name', models.TextField(default='', max_length=15)),
                ('hdate_establish', models.TextField(default='', max_length=10)),
                ('hcompany_description', models.TextField(default='', max_length=60)),
                ('hmission', models.TextField(default='', max_length=80)),
                ('hvission', models.TextField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qfull_name', models.TextField(default='', max_length=120)),
                ('qbirthday', models.TextField(default='', max_length=10)),
                ('qage', models.IntegerField(default='')),
                ('qaddress', models.TextField(default='', max_length=20)),
                ('gcollege', models.TextField(default='', max_length=20)),
                ('gsecondary_level', models.TextField(default='', max_length=20)),
                ('gprimary_level', models.TextField(default='', max_length=20)),
                ('qbranch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='LMList.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='branch',
            name='bcompany',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='LMList.company'),
        ),
        migrations.AddField(
            model_name='background',
            name='gemployee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='LMList.employee'),
        ),
        migrations.AddField(
            model_name='appointment_details',
            name='kemployee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='LMList.employee'),
        ),
    ]
