# Generated by Django 3.1.6 on 2021-06-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMList', '0004_auto_20210625_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_details',
            name='kemployee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.employee'),
        ),
        migrations.AlterField(
            model_name='background',
            name='gemployee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.employee'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bcompany',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qbranch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMList.branch'),
        ),
    ]
